version: '3.8'
services:
  odoo:
    container_name: odoo
    image: odoo:17
    user: root
    depends_on:
      - db
#   ports:
#      - "10017:8069"
#      - "20017:8072" # live chat
    tty: true
    command: --
    env_file: odoo.env 
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./etc/odoo/odoo.conf:/etc/odoo/odoo.conf
    restart: always
    expose:
      - "8069"
    networks:
      - odoo-net

  db:
    container_name: postgres_16
    image: postgres:16
    user: root
    env_file: db.env
    restart: always
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    networks:
      - odoo-net

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./var/log:/var/log/nginx/
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80" 
      - "443:443" 
    depends_on:
      - odoo
    networks:
      - odoo-net

networks:
  odoo-net:
    driver: bridge
